# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

  # Redirect regels
[[redirects]]
  from = "/blog"
  to = "/blog-artikelen"
  status = 301
  force = true # Zorgt ervoor dat de redirect altijd gebeurt, zelfs als /blog toevallig een bestaande pagina zou zijn

[[redirects]]
  from = "/blog/*"
  to = "/blog-artikelen/:splat"
  status = 301
  force = true # Zorgt ervoor dat de redirect altijd gebeurt voor alle subpaden

[[redirects]]
  from = "/over-mij"
  to = "/over-westend-digital"
  status = 301
  force = true # Zorgt ervoor dat de redirect naar de nieuwe over-mij pagina gaat

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
[images]
  remote_images = ['https://mediumturquoise-sparrow-543006.hostingersite.com/*']

# HTML van de toolpagina: altijd vers
# 1) Standaard voor alle HTML-routes → altijd vers ophalen
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Robots-Tag = "all"   # optioneel; zorg iig dat er nergens 'noindex' staat

# 2) Overrides voor statische assets → lang cachen
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
